### ISSUE TITLE
Occasional panics when using the develop branch

### ISSUE THREAD

**Issue by b0d0nne11** [mailgun/kafka-pixy#58]
Kafka-pixy will occasionally panic when running the `maxim/develop` branch.

```
Apr 15 17:00:46.462 INFO  [sarama] client/coordinator coordinator for consumergoup ledger_reboot is #0 (kafka1.ord2.postgun.com:9092)
Apr 15 17:00:46.462 INFO  </offsetManagerFactory[0]/watch4Changes[0]/reassign[160044]> unassign /offsetManagerFactory[0]/ledger_reboot:iad_pipeline_events:8[0] -> /offsetManagerFactory[0]/broker:0[0] (ref=61)
Apr 15 17:00:46.462 INFO  </offsetManagerFactory[0]/watch4Changes[0]/reassign[160044]> assign /offsetManagerFactory[0]/ledger_reboot:iad_pipeline_events:8[0] -> /offsetManagerFactory[0]/broker:0[0] (ref=62)
Apr 15 17:00:46.462 INFO  </offsetManagerFactory[0]/watch4Changes[0]/reassign[160044]> leaving
Apr 15 17:00:46.529 INFO  </offsetManagerFactory[0]/ledger_reboot:pipeline_events:5[0]/processCommits[0]> schedule reassign: reason=offset commit failed, err=(request timeout)
Apr 15 17:00:46.551 INFO  </offsetManagerFactory[0]/ledger_reboot:iad_pipeline_events:10[0]/processCommits[0]> leaving
Apr 15 17:00:46.551 INFO  </consumer[0]/watch4Changes[0]> reassign: change={created=0, outdated=0, closed=1}
Apr 15 17:00:46.551 INFO  </consumer[0]/watch4Changes[0]/reassign[35]> entered: [{created=0, outdated=0, closed=1}]
Apr 15 17:00:46.551 INFO  </offsetManagerFactory[0]/watch4Changes[0]/reassign[160045]> entered: [{created=0, outdated=0, closed=1}]
Apr 15 17:00:46.551 INFO  </consumer[0]/watch4Changes[0]/reassign[35]> unassign /consumer[0]/iad_pipeline_events:10[0] -> /consumer[0]/broker:4[0] (ref=12)
Apr 15 17:00:46.551 INFO  </offsetManagerFactory[0]/watch4Changes[0]/reassign[160045]> unassign /offsetManagerFactory[0]/ledger_reboot:iad_pipeline_events:10[0] -> /offsetManagerFactory[0]/broker:0[0] (ref=61)
Apr 15 17:00:46.551 INFO  </consumer[0]/watch4Changes[0]/reassign[35]> leaving
2016/04/15 17:00:46 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 160745 [running]:
net/http.(*conn).serve.func1(0xc823b0ba80)
        /opt/go/src/net/http/server.go:1389 +0xc1
panic(0x8554a0, 0xc8200120a0)
        /opt/go/src/runtime/panic.go:426 +0x4e9
github.com/mailgun/kafka-pixy/apiserver.(*T).handleConsume(0xc82010ec30, 0x7f709ba28968, 0xc826846270, 0xc826d33b20)
        /home/mg/goworld/src/github.com/mailgun/kafka-pixy/apiserver/apiserver.go:207 +0x40a
github.com/mailgun/kafka-pixy/apiserver.(*T).(github.com/mailgun/kafka-pixy/apiserver.handleConsume)-fm(0x7f709ba28968, 0xc826846270, 0xc826d33b20)
        /home/mg/goworld/src/github.com/mailgun/kafka-pixy/apiserver/apiserver.go:83 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc8202303a0, 0x7f709ba28968, 0xc826846270, 0xc826d33b20)
        /opt/go/src/net/http/server.go:1618 +0x3a
github.com/mailgun/kafka-pixy/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82010ebe0, 0x7f709ba28968, 0xc826846270, 0xc826d33b20)
        /home/mg/goworld/src/github.com/mailgun/kafka-pixy/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/mailgun/kafka-pixy/vendor/github.com/mailgun/manners.(*gracefulHandler).ServeHTTP(0xc82020a3a0, 0x7f709ba28968, 0xc826846270, 0xc826d33b20)
        /home/mg/goworld/src/github.com/mailgun/kafka-pixy/vendor/github.com/mailgun/manners/server.go:333 +0x7e
net/http.serverHandler.ServeHTTP(0xc820111000, 0x7f709ba28968, 0xc826846270, 0xc826d33b20)
        /opt/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc823b0ba80)
        /opt/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /opt/go/src/net/http/server.go:2137 +0x44e
Apr 15 17:00:46.554 INFO  </smartConsumer[0]/ledger_reboot[0]/iad_pipeline_events:10[0]> partition released
Apr 15 17:00:46.554 INFO  </smartConsumer[0]/ledger_reboot[0]/iad_pipeline_events:10[0]> leaving
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0x5b422e]

goroutine 135 [running]:
panic(0x8554a0, 0xc8200120a0)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/mailgun/kafka-pixy/consumer.(*exclusiveConsumer).run(0xc8205b45a0)
        /home/mg/goworld/src/github.com/mailgun/kafka-pixy/consumer/smart_consumer.go:342 +0xc2e
github.com/mailgun/kafka-pixy/consumer.(*exclusiveConsumer).(github.com/mailgun/kafka-pixy/consumer.run)-fm()
        /home/mg/goworld/src/github.com/mailgun/kafka-pixy/consumer/smart_consumer.go:260 +0x20
github.com/mailgun/kafka-pixy/consumer.spawn.func1(0xc8205b4618, 0xc820192980)
        /home/mg/goworld/src/github.com/mailgun/kafka-pixy/consumer/utils.go:16 +0x44
created by github.com/mailgun/kafka-pixy/consumer.spawn
        /home/mg/goworld/src/github.com/mailgun/kafka-pixy/consumer/utils.go:17 +0x56
```

**Comment by horkhe** [comment]
@b0d0nne11 I am pretty sure this has been fixed by the recent changes in master. I redeployed the latest master on the hosts where the issue had been occurring. If the issue won't reproduce by the end of the next week (5/6/2016), then I will close this issue.

**Comment by horkhe** [comment]
The issue has been fixed during refactoring.
