### ISSUE TITLE
Panic in partition consumer

### ISSUE THREAD

**Issue by horkhe** [mailgun/kafka-pixy#82]
From a production log:
```
</_[0]/cons[0]/G:kraken[0]/P:iad_ml_count_events_0[0]> paniced: runtime error: invalid memory address or nil pointer dereference, stack=goroutine 254 [running]:
runtime/debug.Stack(0xc420b219f8, 0x7215a0, 0xc420012030)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/mailgun/kafka-pixy/actor.Spawn.func1.1(0xc4202c7c80)
	/go/src/github.com/mailgun/kafka-pixy/actor/actor.go:63 +0xe5
panic(0x7215a0, 0xc420012030)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/mailgun/kafka-pixy/consumer/partitioncsm.(*T).run(0xc420100ab0)
	/go/src/github.com/mailgun/kafka-pixy/consumer/partitioncsm/partitioncsm.go:151 +0xba7
github.com/mailgun/kafka-pixy/consumer/partitioncsm.(*T).(github.com/mailgun/kafka-pixy/consumer/partitioncsm.run)-fm()
	/go/src/github.com/mailgun/kafka-pixy/consumer/partitioncsm/partitioncsm.go:60 +0x2a
github.com/mailgun/kafka-pixy/actor.Spawn.func1(0xc420100b28, 0xc4202c7c80, 0xc420a9b7d0)
	/go/src/github.com/mailgun/kafka-pixy/actor/actor.go:68 +0xca
created by github.com/mailgun/kafka-pixy/actor.Spawn
	/go/src/github.com/mailgun/kafka-pixy/actor/actor.go:69 +0x58
```

**Comment by horkhe** [comment]
The partition consumer had been rewritten, and I have not seen this problem since then. So I am closing this as fixed.
